### ISSUE TITLE
Reducing Code duplication and Improving Code structure

### ISSUE THREAD

**Issue by kareemmahlees** [the-sabra/express-tool#4]
Hello Sabra!
I saw your post on Twitter about this project and decided to look at it, You have a nice piece of software created here, well done 👏🏻.

However, I browsed through the code and found some changes that might be improved:
- the `utils` directory is typically used, as the name suggests, to house the utility functions, but the code and files in the directory here are not helper functions they are *vital* functions, so they shouldn't be here they should be in a `lib` directory or something, an excellent example of utility functions is the `rootDir.js` file this file should be in the `utils` directory because it offers a helper function.
- There is a lot of duplicate code in the `executeCommands.js` file, basically, they are all the same function except for changing the arguments, so they all can be abstracted into a single function that receives the arguments dynamically.
- In `createProjectFiles.js` in the `packageJsonGenerator` function I see you are creating the `package.json` file manually, couldn't you just exec the `npm init -y` command?
- I noticed that there are two lock files in here, one for `yarn` and the other for `pnpm`, which one are you using? this will confuse anyone wanting to contribute to the project because they don't know what package manager the project is using.

So as not only doing criticism, if you agree with me on the above changes, I can happily create a pull request integrating those changes 🙂.

**Comment by thesabrah** [comment]
Thank you, Kareem, for your feedback. I agree about all the changes you need. However, I created the `packageJsonGenerator` function because I want to install different dependencies in different Templates. about the package manager, I use `npm` for the project but when published in all package managers he gives me these files to publish I don't know about I published the incorrect way or not but if you have time you can create a pull request please test all templates in all package managers because we need stable version, Thank you for your advice, it helped me to see some problems that I didn't see before.
